import Link from "next/link";
import s from "../../legal.module.css";
export const metadata = { title: "Home Backup Power Buying Guide | Pasifika Bazaar", description: "Compare portable power stations for outages, remote homes and everyday backup." };
export default function Guide(){return <main className={s.page}><header className={s.header}><Link className={s.brand} href="/">Pasifika<span>Bazaar</span></Link><Link href="/guides">All guides</Link></header><article className={s.article}><small>HOME & REMOTE LIVING</small><h1>A Practical Guide to Home Backup Power</h1><p className={s.updated}>Updated September 2026 · About 7 minutes</p>
<section><h2>Decide what must keep running</h2><p>Begin with a short list rather than buying the largest unit you can find. Phones, lights and a modem use relatively little energy. Refrigerators, pumps, kettles, heaters and cooking appliances can demand much more. Write down each device’s running watts and consider its starting surge. A power station must handle both its total continuous load and any short surge.</p></section>
<section><h2>Understand watts and watt-hours</h2><p>Watts describe how much power a device needs at one moment. Watt-hours describe stored energy. As a simple estimate, divide usable watt-hours by the load in watts to calculate operating time. Real runtime will be lower than the headline capacity because of inverter losses, standby use, temperature and battery-protection reserves.</p><p>For example, a 1,000 Wh unit will not deliver a full 1,000 Wh through its AC outlets. Build in a sensible margin and avoid relying on an optimistic marketing estimate.</p></section>
<section><h2>Battery chemistry and charging</h2><p>Lithium iron phosphate (often shown as LiFePO4 or LFP) is popular for frequent use because it generally offers long cycle life and good thermal stability. Other lithium chemistries can provide lower weight. Compare the manufacturer’s stated cycle life using the same remaining-capacity benchmark.</p><p>Check how quickly the unit recharges from mains power and whether solar charging is supported. For solar, the panel voltage, current and connector must fall within the power station’s specified input range. A solar input figure is a maximum under suitable conditions, not a promise of daily output.</p></section>
<section><h2>Safety and realistic expectations</h2><p>Use the product exactly as instructed and keep ventilation openings clear. Do not expose it to rain unless the manufacturer expressly rates it for that use. Extension leads and high-load appliances require care. A portable power station is not a substitute for a compliant home electrical installation, and it must never be connected into household wiring without an appropriately licensed electrician and approved equipment.</p></section>
<section><h2>Comparison checklist</h2><ul><li>Essential devices and their starting and running wattage</li><li>Usable battery capacity, not capacity alone</li><li>AC output waveform and continuous/surge ratings</li><li>Battery chemistry, cycle life and replacement support</li><li>Mains and solar recharge times</li><li>Warranty service available where you live</li><li>Weight, noise and portability</li></ul></section>
<section><h2>Editorial note</h2><p>This is general purchasing information, not electrical or emergency-management advice. Prices, shipping and specifications must be confirmed with the retailer. Pasifika Bazaar may earn from clearly marked affiliate links. <Link href="/affiliate-disclosure">Read our disclosure</Link>.</p></section>
</article></main>} 