-- Applied to the Pasifika Bazaar Supabase project.
create extension if not exists pgcrypto;
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,sort_order integer not null default 0,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(),category_id uuid references public.categories(id) on delete set null,name text not null,slug text not null unique,description text not null default '',sku text unique,price_aud_cents integer not null check(price_aud_cents>=0),stock_quantity integer not null default 0 check(stock_quantity>=0),image_url text,badge text,is_active boolean not null default false,is_featured boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),stripe_checkout_session_id text not null unique,stripe_payment_intent_id text,status text not null default 'paid',customer_email text,customer_name text,customer_phone text,currency text not null default 'aud',subtotal_cents integer not null default 0,shipping_cents integer not null default 0,total_cents integer not null default 0,shipping_address jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id) on delete set null,product_name text not null,sku text,unit_price_cents integer not null,quantity integer not null check(quantity>0),created_at timestamptz not null default now());
create table if not exists public.seller_applications(id uuid primary key default gen_random_uuid(),business_name text not null,contact_name text,email text not null,phone text,country text not null,products_description text not null,status text not null default 'new',created_at timestamptz not null default now());
create table if not exists public.admins(user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz not null default now());
alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.seller_applications enable row level security; alter table public.admins enable row level security;
